server:
  port: 8086


spring:
  application:
    name: pos-delivery
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true # 注册到 Eureka-Server，默认为 true
    fetch-registry: true # 从 Eureka-Server 获取注册表，默认为 true
    service-url:
      defaultZone: http://localhost:8761/eureka

